[package]
name = "sun-sets-gtk-theme"
description = "Set GTK Theme based on the sun position"
version = "0.1.0"
authors = ["EdJoPaTo <sun-sets-gtk-theme-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dirs-next = "2"
heliocron = "0.5"
toml = "0.5"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
